env:
  browser: true
  jquery: true
  es2021: true
  webextensions: true


parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - "jquery"

extends:
  - "eslint:recommended"
  - "plugin:jquery/slim"

globals:
  ChromeUtils: "readonly"

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
